// <auto-generated />
using System;
using MasterclassPostgres.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MasterclassPostgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MasterclassPostgres.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MasterclassPostgres.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("en-us")
                        .HasColumnName("default_language");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("CategoryId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("MasterclassPostgres.Models.Category", b =>
                {
                    b.OwnsOne("MasterclassPostgres.Models.Heading", "Heading", b1 =>
                        {
                            b1.Property<int>("CategoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Slug")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("varchar")
                                .HasColumnName("slug");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("varchar")
                                .HasColumnName("title");

                            b1.HasKey("CategoryId");

                            b1.HasIndex("Slug")
                                .IsUnique()
                                .HasDatabaseName("idx_categories_slug");

                            b1.ToTable("categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("Heading")
                        .IsRequired();
                });

            modelBuilder.Entity("MasterclassPostgres.Models.Product", b =>
                {
                    b.HasOne("MasterclassPostgres.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MasterclassPostgres.Models.Heading", "Heading", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("integer");

                            b1.Property<string>("Slug")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("varchar")
                                .HasColumnName("slug");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("varchar")
                                .HasColumnName("title");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Slug")
                                .IsUnique()
                                .HasDatabaseName("idx_products_slug");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Heading")
                        .IsRequired();
                });

            modelBuilder.Entity("MasterclassPostgres.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
